name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  version_code: 10001
  version: 1.0.1

jobs:
  build_android:
    name: Build for Android

    strategy:
      matrix:
        runtime: [android-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.2.0
        with:
          dotnet-version: '10.0.108'

      - name: Setup JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup additional tools
        run: |
          sudo apt-get update
          sudo apt-get -y install strip-nondeterminism

      - name: Save decoded keystore
        id: save_decoded_keystore
        uses: timheuer/base64-to-file@v2
        with:
          fileName: 'keystore.jks'
          encodedString: ${{ secrets.ANDROID_SIGNING_KEYSTORE_BASE64 }}

      - name: Install Android Workload
        run: dotnet workload install android

      - name: Run unit tests
        run: >
          dotnet test 'src/ChronoRover.Tests/ChronoRover.Tests.csproj'
          -c 'Release'
          -r 'android-x64'
          -v 'normal'

      - name: Publish
        run: >
          dotnet publish 'src/ChronoRover.Android/ChronoRover.Android.csproj'
          -o 'binaries'
          -c 'Release'
          -r '${{ matrix.runtime }}'
          -v 'normal'
          -p:AndroidKeyStore=False
          -p:ApplicationVersion=${{ env.version_code }}
          -p:ApplicationDisplayVersion=${{ env.version }}
          -p:AndroidPackageFormat='apk'
          -p:RunAOTCompilation=False
          -p:AndroidEnableProfiledAot=False
          -p:AndroidUseAssemblyStore=False
          -p:AndroidEnableAssemblyCompression=False
          -p:ContinuousIntegrationBuild=True
          -p:Deterministic=True

      - name: Strip timestamps from apk
        run: |
          cp binaries/com.cho3ek89.ChronoRover.apk binaries/com.cho3ek89.ChronoRover-1.apk
          strip-nondeterminism --timestamp=0 --verbose --type=zip binaries/com.cho3ek89.ChronoRover-1.apk

      - name: Align apk
        run: |
          $ANDROID_HOME/build-tools/36.0.0/zipalign -P 16 -f -v 4 binaries/com.cho3ek89.ChronoRover-1.apk binaries/com.cho3ek89.ChronoRover-2.apk

      - name: Sign apk
        run: >
          $ANDROID_HOME/build-tools/36.0.0/apksigner sign
          --ks '${{ steps.save_decoded_keystore.outputs.filePath }}'
          --ks-key-alias ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          --ks-pass pass:${{ secrets.ANDROID_SIGNING_KEYSTORE_PASS }}
          --key-pass pass:${{ secrets.ANDROID_SIGNING_KEY_PASS }}
          --out binaries/ChronoRover_${{ matrix.runtime }}_${{ env.version }}.apk
          binaries/com.cho3ek89.ChronoRover-2.apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          archive: false
          path: binaries/ChronoRover_${{ matrix.runtime }}_${{ env.version }}.apk



  build_desktop:
    name: Build for Desktop

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        runtime: [win-x64, linux-x64]
        exclude:
          - os: windows-latest
            runtime: linux-x64
          - os: ubuntu-latest
            runtime: win-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.2.0
        with:
          dotnet-version: '10.0.108'

      - name: Run unit tests
        run: >
          dotnet test 'src/ChronoRover.Tests/ChronoRover.Tests.csproj'
          -c 'Release'
          -r '${{ matrix.runtime }}'
          -v 'normal'

      - name: Publish
        run: >
          dotnet publish 'src/ChronoRover.Desktop/ChronoRover.Desktop.csproj'
          -o 'binaries'
          -c 'Release'
          -r '${{ matrix.runtime }}'
          -v 'normal'
          -p:Version=${{ env.version }}
          -p:PublishAot=True
          -p:ContinuousIntegrationBuild=True
          -p:Deterministic=True

      - name: Upload artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ChronoRover_${{ matrix.runtime }}_${{ env.version }}
          compression-level: 9
          path: |
            binaries/
            !binaries/**/*.pdb
